### PR TITLE
Fix carons

### PR DESCRIPTION
**Pull request by Finii**
**[why]**
The carons are all upside down and look like a small circumflex. The dcaron and tcaron use a caron instead of an apothrophe.

**[how]**
- Flip caron glyph
- Add combining-comma-above-right (shortened version from comma)
- Recreate dcaron and tcaron from d/t and that new glyph
- Increase version number (patchlevel by one)
- Mention Rodrigo in copyright.

See also
* https://github.com/ryanoasis/nerd-fonts/issues/1492

### CODE REVIEW

**Comment by Finii** [comment]
image

https://github.com/ryanoasis/nerd-fonts/issues/1492#issuecomment-1913622481

**Comment by Finii** [comment]
image

**Comment by Finii** [comment]
This does not **build** the font files, it just changes the `sfd`.
So probably you want to build before merging to your fork.

This is now used for Nerd Fonts, see 
* https://github.com/ryanoasis/nerd-fonts/pull/1546

**Comment by jesusmgg** [comment]
Looks great, let's merge this.

**Pull request merged**
